// <auto-generated />
using System;
using CommonDataInterface.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommonDataInterface.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240505184725_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CommonDataInterface.Models.EHR_PastHistoryRecord", b =>
                {
                    b.Property<string>("RECORDID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ALLERGYLIST_HCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ALLERGY_QT1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BLOODTRANSLIST_HCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHILDRENDISEASELIST_HCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CJQK_QTCJ1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CONFIRMDATE_EXZL")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CONFIRMDATE_GXB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CONFIRMDATE_GXY")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CONFIRMDATE_GZJB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CONFIRMDATE_JHB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CONFIRMDATE_MXZSXFJB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CONFIRMDATE_NZZ")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CONFIRMDATE_QT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CONFIRMDATE_QT2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CONFIRMDATE_QT3")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CONFIRMDATE_QT4")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CONFIRMDATE_QT5")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CONFIRMDATE_TNB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CONFIRMDATE_XTJX")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CONFIRMDATE_ZXJSJB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CONFIRMDATE_ZYB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CREATEDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATEUNIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEUSER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISABILITYLIST_HCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DISABILITYLIST_HCODE_SJ")
                        .HasColumnType("datetime2");

                    b.Property<string>("DISEASELIST_HCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISEASETEXTYCBS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISEASETEXT_EXZL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISEASETEXT_QT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISEASETEXT_QT2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISEASETEXT_QT3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISEASETEXT_QT4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISEASETEXT_QT5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISEASETEXT_SS0")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISEASETEXT_SS1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISEASETEXT_SS2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISEASETEXT_SS3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISEASETEXT_SS4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISEASETEXT_SX0")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISEASETEXT_SX1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISEASETEXT_SX2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISEASETEXT_SX3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISEASETEXT_SX4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISEASETEXT_WS0")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISEASETEXT_WS1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISEASETEXT_WS2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISEASETEXT_WS3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISEASETEXT_WS4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DISEASETEXT_ZYB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMPIID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EXPOSURELIST_HCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FATHERDISEASELIST_HCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GENERALSIGNS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GENETICDISEASELIST_HCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LASTMODIFYDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("LASTMODIFYUNIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LASTMODIFYUSER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOTHERDISEASELIST_HCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OPERATIONLIST_HCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QT_FQ1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QT_MQ1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QT_XDJM1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QT_ZN1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SIBLINGDISEASELIST_HCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("STARTDATE_SS0")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("STARTDATE_SS1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("STARTDATE_SS2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("STARTDATE_SS3")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("STARTDATE_SS4")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("STARTDATE_SX0")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("STARTDATE_SX1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("STARTDATE_SX2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("STARTDATE_SX3")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("STARTDATE_SX4")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("STARTDATE_WS0")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("STARTDATE_WS1")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("STARTDATE_WS2")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("STARTDATE_WS3")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("STARTDATE_WS4")
                        .HasColumnType("datetime2");

                    b.Property<string>("STATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRAUMALIST_HCODE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RECORDID");

                    b.ToTable("EHR_PASTHISTORYRECORD");
                });

            modelBuilder.Entity("CommonDataInterface.Models.Mpi_DemographicInfo", b =>
                {
                    b.Property<string>("EMPIID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BIRTHDAY")
                        .HasColumnType("datetime2");

                    b.Property<string>("BLOODTYPECODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BZ2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CARDNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CENTERPID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CERTIFICATENO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CERTIFICATETYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("COMPLETEPERCENT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CONTACT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CONTACTPHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CONTACTRELATION")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CREATETIME")
                        .HasColumnType("datetime2");

                    b.Property<string>("CREATEUNIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CREATEUSER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CYZK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CZRK")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EDUCATIONCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FAMILYID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HJDCUN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HJDJW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HJDLH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HJDMPH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HJDNONG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HJDSHE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HJDSHI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HJDXIA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HJDXNG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HJDXZQH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HOMEADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HOMEPLACE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HZLX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HZLY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IDCARD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INSURANCECODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INSURANCETEXT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INSURANCETYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISNH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JZDCUN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JZDJW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JZDLH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JZDMPH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JZDNONG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JZDSHE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JZDSHI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JZDXIA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JZDXNG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JZDXZQH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LASTMODIFYTIME")
                        .HasColumnType("datetime2");

                    b.Property<string>("LASTMODIFYUNIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LASTMODIFYUSER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LIVESTOCKCOLUMN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LXRGX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MARITALSTATUSCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOBILENUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MPIID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAMEPYCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NATIONALITYCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NATIONCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OLD_KEY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OWNERNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERSONGROUP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERSONGROUPCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERSONGROUPPHIS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERSONNAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERSONNAME_PY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHONENUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHOTO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POVERTYPOPULATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QRCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("REGISTEREDPERMANENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RHBLOODCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SCEBEGINDATE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SCEENDDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDDQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEXCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SIGNFLAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("STARTWORKDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("STATE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STATUS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VERSIONNUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VIRTUALCARDNUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WORKCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WORKPLACE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XGBZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YLYL1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YLYL2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YLZH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZIPCODE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EMPIID");

                    b.ToTable("MPI_DEMOGRAPHICINFO");
                });
#pragma warning restore 612, 618
        }
    }
}
